### PR TITLE
Make sure other open dropdowns get closed even if clickoutHandler is not triggered

### PR DESCRIPTION
**Pull request by gutschik**
Implemented a service that handles closing of all opened dropdown components

### CODE REVIEW

**Comment by RSSchermer** [comment]
Thanks once again for contributing :+1: 

This is an interesting case. I think we perhaps should consider this more of a bug than a new feature. I suspect your underlying issue is that open dropdowns don't close when another dropdown is clicked (rather than programmatically opening/closing dropdowns)?

I would say that, unless the other dropdown is a nested dropdown, clicking the other dropdown's toggle button/link is a clickout and thus should cause the opened dropdown to close. The current behavior then should perhaps be considered a bug in [the clickoutHandler code](https://github.com/RSSchermer/ember-rl-dropdown/blob/707eb4beb4ae85f7b8c5f216c19c87c16b564670/addon/mixins/rl-dropdown-component.js#L72-L91).

The bug is rather obvious: the clickoutHandler tests if the click *is not* a 'clickin' (a click on the dropdown's toggle or dropdown itself) rather than if the click *is* a 'clickout', but to test if the click is a clickin it uses generic classes and thus doesn't differentiate between clickin in the current dropdown and any other dropdowns. 

Now, I actually recall being aware of this when I originally wrote this addon. I remember rather than using generic classes I tried to use `ember-id` attributes that ember attached to the elements it rendered. However, I couldn't get that to work (I think ember was not actually consistent in the id it used which gave me issues) and so I finally settled on the current implementation.

This, however, was in the Ember 1.10 days, before html-bars, and I think that perhaps another attempt at fixing the `clickoutHandler` now would be worthwhile. It could be that it still can't be done in a nice way and then perhaps this service-based approach is the best solution. If it's the case that this service-based approach is indeed the best way, then it needs to address the case of nested dropdowns. I would also say that the default behavior should be to close the other dropdowns rather then leave them open. This is a BC break of course, but I think in this case that would be the correct thing to do. To allow dropdowns to remain open I think perhaps an option to do `closeOnClickout=false` should be added.

If all of this makes sense to you, then I would propose that I first look into fixing the `clickoutHandler` (you've caught in a busy week, might take me a few days to get around to). If the `clickoutHandler` can't be fixed nicely, then we look into modifying this PR to fix it with a service based approach.

**Comment by gutschik** [comment]
good point on fixing the ```clickoutHandler``` prior to implementing this service. I felt like taking a sledgehammer to crack a nut. 

I was curious why the  ```clickoutHandler``` was triggered by every single click inside our app but the click on the toggle-button itself. And - once again - it's related to ```event.stopPropagation()```, see https://github.com/RSSchermer/ember-rl-dropdown/blob/master/addon/components/rl-dropdown-toggle.js#L29

If ```propagateClicks```is set to false, it's all good. 

Any idea on how to keep both the functionality of disabling propagation *and* triggering the click on the document?

**Comment by RSSchermer** [comment]
I'm not quite sure I understand.

Suppose two dropdowns, A and B. A is open. Currently I expect that clicking B's toggle will not close A, regardless of whether `propagateClicks` is true or false on B's toggle button.

If the `clickoutHandler` is fixed, and `propagateClicks` is false on B's toggle button, then I expect A will still not close, because the click event will not propagate to the document on which the `clickoutHandler` is bound. This will remain a separate issue. I'm not sure what the best way to handle that case would be.

**Comment by RSSchermer** [comment]
Sorry for the delay.

Finally had some time to do some testing. It seems I have been more clever than I was able to recall and in fact the `clickoutHandler` does seem to work as intended (clicking the toggle button of another dropdown does close other opened dropdowns).

The problem only comes up when you set `propagateClicks` to `false`. This makes sense: the clickout event handler is attached to the document, but as the event is intercepted (propagation is stopped), the click event never reaches the document.

Your service-based solution might indeed address this, however, I don't think it's worth increasing the complexity of this project considerably by doing so, only to address a somewhat narrow use case.

If I recall correctly your use case looks something like this:

```hbs
<ul>
  {{#each items as |item|}}
    <li {{action 'doSomething' item}}>
      {{item.name}}
      {{#rl-dropdown-container}}
        ...
      {{/rl-dropdown-container}}
    </li>
  {{/each}}
</ul>
```

You have a `doSomething` click action bound to an element that contains a dropdown and you don't want clicks on the dropdown to fire `doSomething`. Could you not perhaps deal with this in the action handler?

Now, as of 2.0 unfortunately Ember no longer passes the event to an action handler, so you'd need to use a component instead of the `li` and use the `click` handler (which should still get the event as a parameter):

```hbs
<ul>
  {{#each items as |item|}}
    {{item-component item=item action="doSomething"}}
  {{/each}}
</ul>
```

```hbs
<!-- item-component template -->
{{item.name}}
{{#rl-dropdown-container}}
  ...
{{/rl-dropdown-container}}
```

```js
// item-component
export default Ember.Component.extend({
  tagName: 'li',

  click(event) {
    let $target = Ember.$(event.target);

    if($target.closest('html').length && 
       !$target.closest(Ember.$('.rl-dropdown-toggle')).length && 
       !$target.closest(Ember.$('.rl-dropdown')).length) {
      this.sendAction(this.get('item'));
    } // else do nothing
  }
});
```

This is analogous to what the `clickoutHandler` itself does to check if the click was inside or outside the dropdown.

I've not yet tested this snippet. Let me know if this works; if it does not work I'd be happy to set up a dummy app to dig into this further. I'm reasonably certain an approach similar that what I'm suggesting could work for you.

**Comment by gutschik** [comment]
I'm also sorry for the late answer.... :)

First of all thanks for digging more into the issue. 

I agree with you in terms of sticking to the DOM hierarchie and its propagation behaviour, but I honestly disagree when it comes to functionality and code simplicity.
 
I doubt that a local component should to address this issue. First of all, imagine you'd have more 3rd party plugins with special cases like this and you then need to handle all of this in your components (or views) ```actions``` - this would lead to a nightmare. Secondly this creates unnecessary dependencies. And last not least it's not good fashion to use DOM selectors, I try to avoid them im all of my Ember projects. 

I think if there is a setting ```propagateClicks=false``` and another (upcoming) one ```closeOthersOnOpen=true```, then they really should work together.

Besides the fact that it (somehow) increases the complexity of the plugin, are there any other downsides? 

Cheers, Ben

**Comment by RSSchermer** [comment]
> I doubt that a local component should to address this issue. First of all, imagine you'd have more 3rd party plugins with special cases like this and you then need to handle all of this in your components (or views) actions - this would lead to a nightmare. 

I'm not sure I agree.  

I don't think having a click handler on an element but not wanting it to be triggered by clicks on certain child elements is common behavior. I think the child element in question being an `rl-dropdown` component is probably even less common. It doesn't really seem to be an issue that's specific to the `rl-dropdown` components; any component that involves interaction through clicking really has the same issue. So one might turn that reasoning around: should all these components implement options to stop event propagation? Or should this be the concern of that one special parent component that wants to filter out clicks on some of it's child elements?

> Secondly this creates unnecessary dependencies.

On jQuery? jQuery is not probably not necessary to implement my example. The only thing it conveniently implements is the `closest()` method, but a quick Google search turns up some [vanilla JS alternatives](http://clubmate.fi/jquerys-closest-function-and-pure-javascript-alternatives/).

> And last not least it's not good fashion to use DOM selectors, I try to avoid them im all of my Ember projects.

Why not? I think it is probably bad/unnecessary to *manipulate the DOM* through query selectors. Ember abstracts that away and allows you to use templating instead, which is indeed a far superior approach in my opinion. However, I don't think there's anything wrong with using query selectors to check an event source. In fact, I don't think this addon's clickout behaviour could be implemented without it.

Another thing to consider is that the issue is really not just about the `rl-dropdown` components in particular stopping click propagation. Stopping click propagation in general will break this addon. Any other component that stops click propagation will also cause the issue of dropdowns not closing. The service-based solution will at best only deal with other `rl-dropdown` components stopping event propagation. Other elements stopping event propagation will remain an issue. Fortunately it does not seem to be common for Ember components to stop click propagation. In fact, I think this might be the only component that does this. It's perhaps somewhat ironic that this is the only component that breaks its own behavior.

> I honestly disagree when it comes to functionality and code simplicity.

I think code simplicity is a feature. It's easier to test, easier to maintain, easier for potential contributors to understand. That said, I would not shy away from increasing code complexity if it addresses an important, somewhat common use-case. However, I feel yours is probably a very narrow use case. In fact I would not be surprised if you were the only one facing this issue currently.

I understand wanting to keep your application code as lean as possible. I too strive to abstract away as much as possible into more general solutions such as this addon, rather than bloat my application. But I think this is perhaps a specific enough problem that it ought to be addressed by your application, rather than this addon.

**Comment by gutschik** [comment]
>>  Secondly this creates unnecessary dependencies.

> On jQuery? jQuery is not probably not necessary to implement my example. The only thing it conveniently implements is the closest() method, but a quick Google search turns up some vanilla JS alternatives.

Oh no, no. of course not jQuery, I meant from the local ```li``` component to the ```rl-dropdown``` component.

**Comment by gutschik** [comment]
> I don't think having a click handler on an element but not wanting it to be triggered by clicks on certain child elements is common behavior.

how about that? 
ezgif-346736079

**Comment by feichngr** [comment]
I'm with @gutschik here.
Not handling the 'click handler in click handler' pattern is kinda problematic, as it is fairly common in application-style products (JIRA has it in its issue list, for Google it's used in their Material design specs).
I think a stronger guarantee that only a single dropdown is open at a time is worth the bit of extra complexity.

**Comment by RSSchermer** [comment]
> Oh no, no. of course not jQuery, I meant from the local li component to the rl-dropdown component.

Apologies, I misunderstood.

> how about that?

I in no way meant to imply that your use case was not a valid use case. Again, apologies if I made that impression. I'm just unsure whether this addon is the place to address it.

@feichngr Thanks for weighing in, I appreciate the additional insight.

Just to be clear:

A fix for the general issue of elements stopping click propagation breaking the clickout handler: yes, would probably merge such a fix regardless of complexity costs.

A fix for the specific sub-issue where the offending element is an `rl-dropdown-toggle` or an `rl-dropdown`: that still feels iffy, also because I'm still not sure about whether `rl-dropdown-toggle` and `rl-dropdown` should be messing with event propagation in the first place. In my research I came across [this article](https://css-tricks.com/dangers-stopping-event-propagation/) that makes a similar point to the one I tried to make above, but perhaps does a better job of explaining it.

I still don't want to dismiss this fix, but it's definitely not a clear-cut case of merge and move on for me.

Some other considerations:

- Adding an attribute (`closeOthersOnOpen`) suggests that this is a new feature that user would need to specifically enable. But should this really be considered a new feature or is this a patch that fixes unexpected/unintended behavior (dropdown staying open when you click outside)? 
- What about nested dropdowns? I fairly certain that this PR would currently break nested dropdowns. There's currently no automated test that verifies if nested dropdowns function properly, I should probably add one.

**Comment by gutschik** [comment]
nevermind, we'll just use our fork then

**Pull request closed without merging**
